### ISSUE TITLE
 duplicate error servoy version 2023.03

### ISSUE THREAD

**Issue by juanetec** [Servoy/svySignature#3]
Hi,
I found an error with Form Container that I have the Pad.
I found this ticket below, look like the same problem but in another component:

https://support.servoy.com/browse/SVY-18133

Could you check that?

Un Saludo
Juan Ramírez

**Comment by juanetec** [comment]
I try that in the new release 2020.03.1, and it shows this error 

`TypeError: Cannot read properties of null (reading 'getContext')
    at new o (signature_pad.min.js:1:1293)
    at $scope.api.init (pad.js:86:28)
    at pad.js:107:18
    at $watchCollectionAction (angular.js:19196:13)
    at Scope.$digest (angular.js:19336:23)
    at Scope.$apply (angular.js:19696:24)
    at done (angular.js:13539:47)
    at completeRequest (angular.js:13796:7)
    at XMLHttpRequest.requestLoaded (angular.js:13701:9)`

**Comment by jcompagner** [comment]
but that is completely different then that 18133 case, that is even an exception inside the 3rd party signature code.

**Comment by tuanway** [comment]
Hi @juanetec Any way you could create a small sample solution that highlights the error? I'm not able to reproduce at the moment.
